Avkdev\DeliveryBundle\Entity\City:
    type: entity
    table: city
    repositoryClass: Avkdev\DeliveryBundle\Entity\CityRepository
    uniqueConstraints:
        name_UNIQUE:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
