<?php

namespace Avkdev\DeliveryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityDistanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityDistanceRepository extends EntityRepository
{
    /**
     * Returns distance index and delivery term
     * @param $departureCity
     * @param $arrivalCity
     * @return array
     */
    public function getDistanceIndex($departureCity, $arrivalCity)
    {
        return $this->createQueryBuilder('cd')
            ->select('cd.costIdx', 'cd.deliveryTime')
            ->where('cd.departureCity = :departure AND cd.arrivalCity = :arrival')
            ->setParameters(array('departure' => $departureCity, 'arrival' => $arrivalCity))
            ->getQuery()
            ->getSingleResult();
    }
}
