<?php

namespace Avkdev\DeliveryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getApiCompaniesList()
    {
        $data = [];
        foreach ($this->findBy(array('dataSource' => Company::DATA_SOURCE_API)) as $entity) {
            $data[] = array(
                'id'   => $entity->getId(),
                'name' => $entity->getName(),
            );
        }
        return $data;
    }
}
