<?php

namespace Avkdev\DeliveryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function getApiCompaniesList()
    {
        return $this->findBy(array('dataSource' => 'api'));
    }
}
