<?php

namespace Avkdev\DeliveryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * PricelistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricelistRepository extends EntityRepository
{
    public function getDataByCalcForm(array $data)
    {
        return $this->createQueryBuilder('p')
            ->select('IDENTITY(p.company) AS company_id', 'MAX(p.cost) AS cost')
            ->join('Avkdev\DeliveryBundle\Entity\Company', 'c', 'WITH', 'c.id = p.company')
            ->where('
                p.size <= :size
                AND p.weight <= :weight
                AND p.parcelCost <= :parcelCost
                AND c.dataSource = :datasource
            ')
            ->groupBy('p.company')
            ->setParameters(array(
                'size'       => $data['size'],
                'weight'     => $data['weight'],
                'parcelCost' => $data['parcel_cost'],
                'datasource' => Company::DATA_SOURCE_DATABASE,
            ))
            ->getQuery()
            ->getArrayResult();
    }
}
